micronaut:
  application:
    name: badevann
  server:
    port: 8080
    cors:
      enabled: true
      configurations:
        web:
          allowed-origins:
            - http://localhost:5173
          allowed-methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS

datasources:
  default:
    url: jdbc:postgresql://localhost:5434/badevann
    driver-class-name: org.postgresql.Driver
    username: badevann
    password: badevann
    dialect: POSTGRES
    schema-generate: NONE

flyway:
  datasources:
    default:
      enabled: true
      locations:
        - classpath:db/migration
      baseline-on-migrate: true

logger:
  levels:
    no.badevann: DEBUG
    io.micronaut.data.query: DEBUG
